// <auto-generated />
namespace day2.EF.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201905081521049_userBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
