// <auto-generated />
namespace day2.EF.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateattrebutesUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateattrebutesUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201905071844257_updateattrebutesUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
